name: Run Test

on:
  push:
    branches:
      - master
      - develop
      - feature/further-ci

  pull_request:
    branches:
      - develop
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      # Runs a single command using the runners shell
      - name: check location and contents surround
        run: "echo pwd: ; pwd; echo ls: ; ls; echo ls ..: ; ls .."

      - name: Run tests
        run: yarn test --testTimeout=50000
