name: Run Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn
      # - name: Run tests
      #   run: yarn test --testTimeout=50000
